local events = {}
Events = events

events.EVT_ITEM_PICKUP = "LUA_EVT_ITEM_PICKUP"
events.EVT_INVENTORY_UPDATED = "LUA_EVT_INVENTORY_UPDATED"
events.EVT_CHARACTER_HEALTH_VALUE_MODIFY = "LUA_EVT_CHARACTER_HEALTH_VALUE_MODIFY"
events.EVT_CHARACTER_ENERGY_VALUE_MODIFY = "LUA_EVT_CHARACTER_ENERGY_VALUE_MODIFY"
events.EVT_CHARACTER_MOOD_VALUE_MODIFY = "LUA_EVT_CHARACTER_MOOD_VALUE_MODIFY"



return events